name: MuteChat
author: Teunboeke 
version: 1.0.0 
main: Teunboeke\MuteChat\Main
api: 3.0.0
description: mute the whole chat with this plugin!

commands:
   MuteChat:
    aliases: [gm]
    description: Enable/Disable Global Mute.
    permission: Mute.Chat
